MCMC:
  - changed-files:
      - any-glob-to-any-file: 
          - mcmc/**

Plotting:
  - changed-files:
      - any-glob-to-any-file: 
          - plotting/**
          - Diagnostics/**

Nu Osc/Xsec:
  - changed-files:
      - any-glob-to-any-file: 
          - covariance/**
          - splines/**

Samples:
  - changed-files:
      - any-glob-to-any-file: 
          - samplePDF/**

Manager:
  - changed-files:
      - any-glob-to-any-file: 
          - manager/**

Documentation:
  - changed-files:
      - any-glob-to-any-file: 
          - Doc/**
