name: Docker CI Alma9

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
  release:
    types: [published]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TagName: ${{ github.event_name == 'release' && 'alma9' + github.event.release.tag_name || 'alma9latest' }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build Docker image
      run: docker build . --file Doc/MaCh3DockerFiles/Alma9/Dockerfile --tag ghcr.io/${{ github.repository_owner }}/mach3:${{ env.TagName }}

    - name: Push Docker image
      run: docker push ghcr.io/${{ github.repository_owner }}/mach3:${{ env.TagName }}
