name: Docker Image CI

on:
  push:
    branches: [ develop, feature_DockerFile ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build the Docker image
      run: docker build . --file Doc/MaCh3DockerFiles/Alma9/Dockerfile --tag ghcr.io/${{ github.repository_owner }}/mach3/mach3:alma9latest

    - name: Push the Docker image to GitHub Container Registry
      run: docker push ghcr.io/${{ github.repository_owner }}/mach3/mach3:alma9latest
