name: Tag MaCh3 Tutorial

on:
  push:
    tags:
      - '*'  # This workflow will trigger on any tag push
    branches:
      - feature_TagCI  # Trigger on commits to this branch

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          repository: mach3-software/MaCh3Validations

      - name: Set up Git
        run: |
          git config --global user.name "MaCh3 Bot"
          git config --global user.email "action@github.com"

      - name: Create and push the new tag
        run: |
          # Debugging: print the GITHUB_REF and TAG_NAME
          echo "GITHUB_REF: ${GITHUB_REF}"
          echo "Using PAT: ${{ secrets.MACH3_VALIDATIONS_PAT }}"

          # Extract the tag name from GITHUB_REF
          #TAG_NAME=$(echo "${GITHUB_REF#refs/tags/}")
          TAG_NAME=1.1.0

          # Create the new tag
          git tag $TAG_NAME

          # Push the tag to the MaCh3Validations repository
          git push https://${{ secrets.MACH3_VALIDATIONS_PAT }}@github.com/mach3-software/MaCh3Validations.git $TAG_NAME
