name: Tag MaCh3 Tutorial

on:
  push:
    tags:
      - '*'  # This workflow will trigger on any tag push
    branches:
      - feature_TagCI  # Trigger on commits to this branch

jobs:
  tag-validations:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow in MaCh3Validations
        run: |
          #TAG_NAME=$(git describe --tags --abbrev=0)
          TAG_NAME=1.1.0
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/mach3-software/MaCh3Validations/git/refs \
            -d '{"ref": "refs/tags/'"$TAG_NAME"'", "sha": "'"$(git rev-parse HEAD)"'"}'
        env:
          GITHUB_TOKEN: ${{ secrets.MACH3_VALIDATIONS_PAT }}
