name: Tag MaCh3 Tutorial

on:
  push:
    tags:
      - '*'  # This workflow will trigger on any tag push
  pull_request:
    branches: [ develop ]

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          repository: mach3-software/MaCh3Validations

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Create and push the new tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Extract the tag name from GITHUB_REF
          TAG_NAME=$(echo "${GITHUB_REF#refs/tags/}")
          git tag $TAG_NAME
          git push https://$GITHUB_TOKEN@github.com/mach3-software/MaCh3Validations.git $TAG_NAME
